Improve UI
MediaComem/geocity-wc-map pull request #29
Opened 2023-03-09 11:29 UTC by gdozot2

There are two things in this PR:

* First, when a setView is applied with new view, all the listener should be updated. Do you think there is a better way or need a comment where this update is done?
* Do you think the time is correct for the warning message outside the border or do you think another solution?

2023-03-09 14:49 UTC, slecorne requested changes

2023-03-09 14:49 UTC, slecorne commented on src/components/mode/create.ts
> +        map.getView().on('change:resolution', () => this.setChangeResolution(map, vectorLayer))
why do we need that? a comment would be good£
and similar for others

2023-03-09 14:49 UTC, slecorne commented on src/styles/controls.css
> +  outline: none !important;
try avoiding !important and adding additional css selector instead

2023-03-09 14:49 UTC, slecorne commented on src/utils/control-icon-manager.ts
> +    }
this code is duplicated in many places, should be probably refactor in an helper function like `registerMapEvent(event, callback)`

2023-03-14 07:51 UTC, gdozot2 commented on src/components/mode/create.ts
> +        map.getView().on('change:resolution', () => this.setChangeResolution(map, vectorLayer))
Comment in the new EventManager

2023-03-14 07:51 UTC, gdozot2 commented on src/styles/controls.css
> +  outline: none !important;
Done

2023-03-14 07:51 UTC, gdozot2 commented on src/utils/control-icon-manager.ts
> +    }
Done

2023-03-14 15:34 UTC, slecorne approved these changes

2023-03-14 15:34 UTC, merged